"""Curated beginner glossary: fixed, reviewed definitions for the concepts a first-time Indian
investor asks about. Nothing here is generated by a model, so an answer from this file can
never contain an invented price, return or ticker.

Rules for editing an entry:
- Plain language first; jargon is explained inline.
- The `example` is a tiny rupee illustration of the idea (arithmetic only), never a claim
  about a real security, a market level, or what an investment "will" earn.
- No tax rates, fees or limits that change with the Budget; point to "current rules".
"""

from __future__ import annotations

import re
from dataclasses import dataclass


@dataclass(frozen=True)
class GlossaryEntry:
    term: str
    aliases: tuple[str, ...]
    definition: str
    example: str


GLOSSARY: tuple[GlossaryEntry, ...] = (
    GlossaryEntry(
        "ETF",
        ("etf", "etfs", "exchange traded fund", "exchange-traded fund"),
        "An ETF (exchange-traded fund) is a basket of investments, for example all 50 companies "
        "in the Nifty 50 index, that you buy and sell on the stock exchange like a single share, "
        "through your demat account.",
        "If one unit of an ETF costs ₹250, ₹1,000 buys 4 units, and those 4 units give you a small "
        "slice of every company in the basket.",
    ),
    GlossaryEntry(
        "SIP",
        ("sip", "sips", "systematic investment plan"),
        "A SIP (systematic investment plan) means investing a fixed amount on a fixed date every "
        "month, usually into a mutual fund. It builds the habit of investing regularly instead of "
        "trying to pick the perfect day.",
        "A ₹5,000 monthly SIP for 12 months puts in ₹5,000 × 12 = ₹60,000 of your own money. "
        "What it is worth later depends on the fund and the market.",
    ),
    GlossaryEntry(
        "Mutual fund",
        ("mutual fund", "mutual funds", "mf"),
        "A mutual fund pools money from many people and a professional fund manager invests it in "
        "shares, bonds or both. You own units of the fund and share its gains and losses in "
        "proportion.",
        "If 1,000 people each put in ₹10,000, the fund has ₹1 crore to invest. Your ₹10,000 is "
        "1/1,000th of it.",
    ),
    GlossaryEntry(
        "NAV",
        ("nav", "net asset value"),
        "NAV (net asset value) is the price of one unit of a mutual fund. It is the fund's total "
        "holdings minus its costs, divided by the number of units, and is published once a day.",
        "If a fund holds ₹100 crore of assets and has 5 crore units, its NAV is ₹20. "
        "Investing ₹2,000 at that NAV gets you 100 units.",
    ),
    GlossaryEntry(
        "Expense ratio",
        ("expense ratio", "ter", "total expense ratio", "fund fees", "fund charges"),
        "The expense ratio is the yearly fee a mutual fund or ETF charges, as a percentage of "
        "your money in it. It is taken out of the fund's value automatically; you never pay it "
        "separately.",
        "On ₹1,00,000 invested, a 1% expense ratio costs ₹1,000 a year; a 0.2% one costs ₹200. "
        "Lower fees leave more of the fund's result with you.",
    ),
    GlossaryEntry(
        "P/E ratio",
        ("p/e", "pe ratio", "p/e ratio", "pe", "price to earnings", "price-to-earnings"),
        "The P/E (price-to-earnings) ratio is a share's price divided by the company's profit per "
        "share over a year. It shows how many rupees you pay for each ₹1 of yearly profit, which "
        "is a rough way to compare how expensive shares are.",
        "A share priced at ₹200 whose company earns ₹10 per share a year has a P/E of 200 ÷ 10 = 20.",
    ),
    GlossaryEntry(
        "ROE",
        ("roe", "return on equity"),
        "ROE (return on equity) is the yearly profit a company makes as a percentage of the money "
        "its owners have put into it. A higher ROE, held steadily over years, usually signals a "
        "well-run business.",
        "If owners have ₹100 crore in a company and it earns ₹15 crore in a year, ROE is 15%.",
    ),
    GlossaryEntry(
        "Market cap",
        ("market cap", "market capitalisation", "market capitalization"),
        "Market cap (market capitalisation) is the total value the stock market puts on a whole "
        "company: share price × number of shares. It is used to call a company large, mid or small.",
        "A company with 10 crore shares trading at ₹500 has a market cap of 10 crore × ₹500 = "
        "₹5,000 crore.",
    ),
    GlossaryEntry(
        "Large cap",
        ("large cap", "large-cap", "largecap", "large caps"),
        "Large-cap companies are the biggest, best-established listed companies (SEBI counts the "
        "top 100 by market value). They tend to swing less than smaller companies, though they "
        "can still fall.",
        "Think of the household-name companies in the Nifty 50: big and established, so usually "
        "steadier than a young small company.",
    ),
    GlossaryEntry(
        "Mid cap",
        ("mid cap", "mid-cap", "midcap", "mid caps"),
        "Mid-cap companies are the next tier after the top 100 (ranked 101 to 250 by market "
        "value). They have room to grow but swing more than large caps.",
        "A mid-cap may double in a good phase and fall sharply in a bad one; large caps usually "
        "move less in both directions.",
    ),
    GlossaryEntry(
        "Small cap",
        ("small cap", "small-cap", "smallcap", "small caps"),
        "Small-cap companies rank beyond the top 250 by market value. They can grow fast but are "
        "riskier: prices swing a lot and they can be hard to sell quickly.",
        "If only a few people trade a small-cap share each day, selling ₹50,000 of it at once "
        "could push its price down.",
    ),
    GlossaryEntry(
        "Index fund",
        ("index fund", "index funds", "index mutual fund"),
        "An index fund is a mutual fund that simply copies a market index such as the Nifty 50, "
        "holding the same companies in the same proportions. It has no star fund manager picking "
        "stocks, so its fees are low.",
        "If the Nifty 50 index rises 1% in a day, an index fund tracking it rises about 1% too, "
        "minus its small fee.",
    ),
    GlossaryEntry(
        "ELSS",
        ("elss", "tax saving fund", "tax saver fund", "tax saving mutual fund"),
        "ELSS (equity-linked savings scheme) is a mutual fund that invests mostly in shares and "
        "can reduce your taxable income under Section 80C, with a lock-in of 3 years, the "
        "shortest among 80C options. Check the current tax rules before relying on it.",
        "Money put in an ELSS fund today cannot be withdrawn for 3 years, even if the market "
        "falls in the meantime.",
    ),
    GlossaryEntry(
        "Demat account",
        ("demat", "demat account", "dmat", "dematerialised account"),
        "A demat account is the account that holds your shares and ETFs electronically, like a "
        "bank account holds money. You need one, linked to a trading account at a broker, to buy "
        "shares in India.",
        "When you buy 3 shares of a company, they appear in your demat account within a day or "
        "two, with no paper certificates.",
    ),
    GlossaryEntry(
        "LTCG",
        ("ltcg", "long term capital gains", "long-term capital gains", "long term capital gain"),
        "LTCG (long-term capital gains) is the tax on profit when you sell listed shares or equity "
        "funds after holding them for more than one year. Long-term profits are taxed differently "
        "from short-term ones; check the current rates and any exemption limit.",
        "Buy at ₹100, sell at ₹130 after 18 months: the ₹30 profit per share is a long-term gain.",
    ),
    GlossaryEntry(
        "STCG",
        ("stcg", "short term capital gains", "short-term capital gains", "short term capital gain"),
        "STCG (short-term capital gains) is the tax on profit when you sell listed shares or equity "
        "funds within one year of buying. Check the current rate before you sell.",
        "Buy at ₹100, sell at ₹120 after 4 months: the ₹20 profit per share is a short-term gain.",
    ),
    GlossaryEntry(
        "Diversification",
        ("diversification", "diversify", "diversified", "diversifying"),
        "Diversification means spreading your money across different companies, sectors and "
        "kinds of investment so that one bad outcome does not hurt you much. It is the "
        "'don't put all your eggs in one basket' rule.",
        "With ₹10,000 in one company, a 20% fall costs you ₹2,000. Spread over 10 companies, "
        "one of them falling 20% costs about ₹200.",
    ),
    GlossaryEntry(
        "Dividend",
        ("dividend", "dividends"),
        "A dividend is a share of its profit that a company pays out to shareholders, per share "
        "you hold. Not every company pays one, and the amount can change or stop.",
        "If a company declares a dividend of ₹5 per share and you hold 20 shares, you receive "
        "20 × ₹5 = ₹100.",
    ),
    GlossaryEntry(
        "IPO",
        ("ipo", "ipos", "initial public offering"),
        "An IPO (initial public offering) is when a company sells its shares to the public for "
        "the first time so that they can start trading on the stock exchange. Applying is not a "
        "guarantee of getting shares, and the price can fall as well as rise after listing.",
        "If an IPO is priced at ₹100 a share with a minimum lot of 100 shares, applying for one "
        "lot needs ₹10,000.",
    ),
    GlossaryEntry(
        "Risk vs return",
        ("risk vs return", "risk and return", "risk return", "risk vs reward", "what is risk"),
        "Risk and return go together: investments that can grow more usually also swing more, and "
        "can lose money, while steadier investments usually grow less. No one can promise a "
        "return, so the aim is a mix whose ups and downs you can live with.",
        "A savings account may grow slowly but safely. Shares can grow faster over many years, "
        "but a ₹10,000 holding may be worth ₹8,000 for a while before it recovers.",
    ),
    GlossaryEntry(
        "Stock market",
        (
            "stock market",
            "share market",
            "how does the market work",
            "how does the stock market work",
            "how does the share market work",
            "how the market works",
            "how the stock market works",
            "stock exchange",
        ),
        "The stock market is a marketplace, mainly the NSE and BSE in India, where buyers and "
        "sellers trade small ownership slices (shares) of listed companies. Prices move "
        "all day as buyers and sellers agree on a price, driven by company news, the economy "
        "and plain demand and supply.",
        "If more people want to buy a share than sell it, its price rises until sellers are "
        "willing to part with it; if more want to sell, it falls.",
    ),
    GlossaryEntry(
        "Share (stock)",
        ("share", "stock", "shares", "stocks", "equity share"),
        "A share (also called a stock) is one small unit of ownership in a company. If you own "
        "shares you own a tiny part of the business and your holding rises and falls with the "
        "company's value.",
        "If a company has 1,00,000 shares and you own 10, you own 0.01% of it.",
    ),
)

_EDU_LEADS = r"(?:what\s+is|what's|whats|what\s+are|what\s+does|explain|meaning\s+of|define|tell\s+me\s+about|how\s+does)"


def _alias_pattern(alias: str) -> re.Pattern[str]:
    return re.compile(rf"(?<![a-z0-9]){re.escape(alias)}(?![a-z0-9])", re.IGNORECASE)


_ALIAS_INDEX: list[tuple[str, GlossaryEntry, re.Pattern[str]]] = sorted(
    (
        (alias, entry, _alias_pattern(alias))
        for entry in GLOSSARY
        for alias in entry.aliases
    ),
    key=lambda item: -len(item[0]),
)

# Bare "share"/"stock"/"shares"/"stocks" appear in nearly every investing question, so they
# only count as an education term when the whole message asks for their definition.
_GENERIC_ALIASES = {"share", "stock", "shares", "stocks", "equity share", "pe", "mf"}

GLOSSARY_ALIAS_WORDS: frozenset[str] = frozenset(
    word.upper() for entry in GLOSSARY for alias in entry.aliases for word in alias.split()
)


def find_term(text: str) -> GlossaryEntry | None:
    """The most specific glossary entry mentioned in `text`, or None."""
    lowered = text.lower().strip()
    for alias, entry, pattern in _ALIAS_INDEX:
        if not pattern.search(lowered):
            continue
        if alias in _GENERIC_ALIASES and not re.fullmatch(
            rf"{_EDU_LEADS}\s+(?:a|an|the)?\s*{re.escape(alias)}\s*[?.!]*", lowered
        ):
            continue
        return entry
    return None


def is_bare_term(text: str) -> bool:
    """True when the whole message is just a glossary term ("ETF?", "the NAV")."""
    lowered = re.sub(r"^(?:a|an|the)\s+", "", text.lower().strip().rstrip("?.! "))
    return any(lowered == alias for entry in GLOSSARY for alias in entry.aliases)


def asks_for_definition(text: str) -> bool:
    return re.search(_EDU_LEADS, text.lower()) is not None


def entry_by_term(term: str) -> GlossaryEntry | None:
    key = term.strip().lower()
    for entry in GLOSSARY:
        if entry.term.lower() == key or key in entry.aliases:
            return entry
    return None
